//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Civilian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Civilian()
        {
            this.helpRequests = new HashSet<helpRequest>();
        }
    
        public string phoneNumber { get; set; }
        public string password { get; set; }
        public string NIDN { get; set; }
        public string fullName { get; set; }
        public string bloodType { get; set; }
        public System.DateTime birthDate { get; set; }
        public string email { get; set; }
        public string medicalCondition { get; set; }
        public string notificationToken { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<helpRequest> helpRequests { get; set; }
    }
}
