//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Collections.Generic;
    
    public partial class helpRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public helpRequest()
        {
            this.ParamedicTeams = new HashSet<ParamedicTeam>();
        }
    
        public int id { get; set; }
        public string civilianPhoneNumber { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> timeOfArrivel { get; set; }
        public Nullable<System.DateTime> timeOfEnd { get; set; }
        public Nullable<int> numberOfHumans { get; set; }
        public Nullable<int> hospital { get; set; }
    
        public virtual Civilian Civilian { get; set; }
        public virtual Hospital Hospital1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParamedicTeam> ParamedicTeams { get; set; }
    }
}
