//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EEmergencyDataBaseEntities : DbContext
    {
        public EEmergencyDataBaseEntities()
            : base("name=EEmergencyDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Announcemet> Announcemets { get; set; }
        public virtual DbSet<Civilian> Civilians { get; set; }
        public virtual DbSet<DCD> DCDs { get; set; }
        public virtual DbSet<helpRequest> helpRequests { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Paramedic> Paramedics { get; set; }
        public virtual DbSet<ParamedicTeam> ParamedicTeams { get; set; }
        public virtual DbSet<RequestLog> RequestLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeamsAssigendLog> TeamsAssigendLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
