//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamedicTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParamedicTeam()
        {
            this.Paramedics = new HashSet<Paramedic>();
        }
    
        public int teamNumber { get; set; }
        public int deploymentLocation { get; set; }
        public string status { get; set; }
    
        public virtual DCD DCD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paramedic> Paramedics { get; set; }
        public virtual helpRequest helpRequest { get; set; }
        public virtual Paramedic Paramedic { get; set; }
    }
}
