//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paramedic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paramedic()
        {
            this.ParamedicTeams = new HashSet<ParamedicTeam>();
        }
    
        public string phoneNumber { get; set; }
        public string password { get; set; }
        public string NIDN { get; set; }
        public string fullname { get; set; }
        public string status { get; set; }
        public string notificationToken { get; set; }
        public int Team { get; set; }
        public string email { get; set; }
    
        public virtual ParamedicTeam ParamedicTeam { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParamedicTeam> ParamedicTeams { get; set; }
    }
}
