//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int id { get; set; }
        public string civilianPhoneNumber { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string description { get; set; }
        public System.DateTime timeOfArrival { get; set; }
        public System.DateTime timeOfEnd { get; set; }
        public Nullable<int> hospital { get; set; }
    
        public virtual Hospital Hospital1 { get; set; }
        public virtual TeamsAssigendLog TeamsAssigendLog { get; set; }
    }
}
