//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationEEmergency
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string phoneNumber { get; set; }
        public string userType { get; set; }
    
        public virtual Civilian Civilian { get; set; }
        public virtual Paramedic Paramedic { get; set; }
        public virtual User Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
