USE [master]
GO

/****** Object:  Database [EEmergencyDataBase]    Script Date: 11/30/2020 6:24:58 PM ******/
CREATE DATABASE [EEmergencyDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EEmergencyDataBase', FILENAME = N'C:\Users\USER\EEmergencyDataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EEmergencyDataBase_log', FILENAME = N'C:\Users\USER\EEmergencyDataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EEmergencyDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EEmergencyDataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EEmergencyDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EEmergencyDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EEmergencyDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EEmergencyDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EEmergencyDataBase] SET  MULTI_USER 
GO

ALTER DATABASE [EEmergencyDataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EEmergencyDataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EEmergencyDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EEmergencyDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EEmergencyDataBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EEmergencyDataBase] SET QUERY_STORE = OFF
GO

USE [EEmergencyDataBase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [EEmergencyDataBase] SET  READ_WRITE 
GO

